# appveyor.yml
image:
  - Visual Studio 2017

init:
  - cmd: dir C:\Qt\5.12.2
  - cmd: qmake --version
  
build_script:
  - cmd: dir
  - qmake
  - cd output
  - windeployqt serialport-tools.exe
  
  