# appveyor.yml
image:
  - Visual Studio 2017

init:
  - cmd: set QT_DIR=C:\Qt\5.12.2\mingw73_32
  - cmd: dir %QT_DIR%
  - cmd: set Path=%QT_DIR%\bin;C:\MinGW\bin;%Path%
  - cmd: qmake --version
  
build_script:
  - cmd: qmake
  - cmd: cd output
  - cmd: windeployqt serialport-tools.exe
  - cmd: dir
  
  