# appveyor.yml
image:
  - Visual Studio 2017

init:
  - cmd: set QT_DIR=C:\Qt\5.12.2\mingw73_32
  - cmd: set PATH=%QT_DIR%\bin;C:\Qt\Tools\mingw730_32\bin;%PATH%
  
build_script:
  - cmd: qmake
  - cmd: mingw32-make
  
after_build:
  - cmd: cd output
  - cmd: del /Q plugins\*.a
  - cmd: windeployqt serialport-tools.exe
  - cmd: set buildname=build%APPVEYOR_BUILD_NUMBER%_%APPVEYOR_REPO_COMMIT:~0,7%
  - cmd: 7z a ..\\Serialport-tools_%buildname%.7z *
  - cmd: cd ..
  - cmd: dir

artifacts:
  - path: '*.7z'
    name: myartifact
  
deploy:
  - provider: GitHub
    tag: appveyor-v%appveyor_build_version%
    release: Serialport-tools-v%appveyor_build_version%
    description: Automated builds (Appveyor)
    auth_token:
      secure: 9SkJXg6/lG0/C2Xu4EPB8EfEn2vkf6Y1dWfa70t7eTyQ7lDRZB0DlXsIMRvztnfk
    artifact: myartifact
    draft: true