# appveyor.yml
image:
  - Visual Studio 2017

init:
  - cmd: set QT_DIR=C:\Qt\5.12.2\msvc2017
  - cmd: set PATH=%QT_DIR%\bin;%PATH%
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmd: qmake --version
  
build_script:
  - cmd: echo %PATH%
  - cmd: qmake
  - cmd: nmake
  
after_build:
  - cmd: cd output
  - cmd: windeployqt serialport-tools.exe
  - cmd: set buildname=build%APPVEYOR_BUILD_NUMBER%_%APPVEYOR_REPO_COMMIT:~0,7%
  - cmd: 7z a ..\\Serialport-tools_%buildname%.7z *
  - cmd: cd ..
  
deploy:
  - provider: GitHub
    tag: appveyor-v%appveyor_build_version%
    release: Serialport-tools-v%appveyor_build_version%
    description: Automated builds (Appveyor)
    auth_token:
      secure: 9SkJXg6/lG0/C2Xu4EPB8EfEn2vkf6Y1dWfa70t7eTyQ7lDRZB0DlXsIMRvztnfk
    artifact: '*.7z'