# appveyor.yml
image:
  - Visual Studio 2017

init:
  - cmd: set QT_DIR=C:\Qt\5.12.2\mingw73_32
  - cmd: dir C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1
  - cmd: set PATH=%QT_DIR%\bin;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\bin;%PATH%
  - cmd: qmake --version
  
build_script:
  - cmd: echo %PATH%
  - cmd: qmake
  - cmd: cd output
  - cmd: windeployqt serialport-tools.exe
  - cmd: dir
  
  